In [99]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [100]:
dataset = pd.read_csv('Dataku.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [101]:
print(x)

[['Taman Impian Jaya Ancol' 100.0 80000.0]
 ['Taman Mini Indonesia Indah' 80.0 50000.0]
 ['Taman Margasatwa Ragunan' 85.0 60000.0]
 ['Taman Impian Jaya Ancol' 90.0 72000.0]
 ['Taman Mini Indonesia Indah' 110.0 52000.0]
 ['Taman Margasatwa Ragunan' 94.0 nan]
 ['Taman Impian Jaya Ancol' nan 90000.0]
 ['Taman Mini Indonesia Indah' 75.0 81000.0]
 ['Taman Margasatwa Ragunan' 120.0 74000.0]
 ['Taman Impian Jaya Ancol' 150.0 88000.0]]


In [102]:
print(y)

[71688. 36977.  6109.     0.   105.    nan   769.    80.   269.   237.]


In [103]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [104]:
print(x)

[['Taman Impian Jaya Ancol' 100.0 80000.0]
 ['Taman Mini Indonesia Indah' 80.0 50000.0]
 ['Taman Margasatwa Ragunan' 85.0 60000.0]
 ['Taman Impian Jaya Ancol' 90.0 72000.0]
 ['Taman Mini Indonesia Indah' 110.0 52000.0]
 ['Taman Margasatwa Ragunan' 94.0 71888.88888888889]
 ['Taman Impian Jaya Ancol' 100.44444444444444 90000.0]
 ['Taman Mini Indonesia Indah' 75.0 81000.0]
 ['Taman Margasatwa Ragunan' 120.0 74000.0]
 ['Taman Impian Jaya Ancol' 150.0 88000.0]]


In [105]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [106]:
print(x)

[[1.0 0.0 0.0 100.0 80000.0]
 [0.0 0.0 1.0 80.0 50000.0]
 [0.0 1.0 0.0 85.0 60000.0]
 [1.0 0.0 0.0 90.0 72000.0]
 [0.0 0.0 1.0 110.0 52000.0]
 [0.0 1.0 0.0 94.0 71888.88888888889]
 [1.0 0.0 0.0 100.44444444444444 90000.0]
 [0.0 0.0 1.0 75.0 81000.0]
 [0.0 1.0 0.0 120.0 74000.0]
 [1.0 0.0 0.0 150.0 88000.0]]


In [107]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [108]:
print(y)

[8 7 6 0 2 9 5 1 4 3]


In [109]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [110]:
print(x_train)

[[1.0 0.0 0.0 100.44444444444444 90000.0]
 [0.0 0.0 1.0 110.0 52000.0]
 [1.0 0.0 0.0 100.0 80000.0]
 [1.0 0.0 0.0 90.0 72000.0]
 [0.0 0.0 1.0 80.0 50000.0]
 [0.0 0.0 1.0 75.0 81000.0]
 [0.0 1.0 0.0 120.0 74000.0]
 [0.0 1.0 0.0 94.0 71888.88888888889]]


In [111]:
print(x_test)

[[0.0 1.0 0.0 85.0 60000.0]
 [1.0 0.0 0.0 150.0 88000.0]]


In [112]:
print(y_train)

[5 2 8 0 7 1 4 9]


In [113]:
print(y_test)

[6 3]


In [114]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [115]:
print(x_train)

[[1.0 0.0 0.0 100.44444444444444 1.4328353023153841]
 [0.0 0.0 1.0 110.0 -1.488355001063819]
 [1.0 0.0 0.0 100.0 0.6641010119524359]
 [1.0 0.0 0.0 90.0 0.04911357966207737]
 [0.0 0.0 1.0 80.0 -1.6421018591364087]
 [0.0 0.0 1.0 75.0 0.7409744409887308]
 [0.0 1.0 0.0 120.0 0.202860437734667]
 [0.0 1.0 0.0 94.0 0.04057208754693362]]


In [116]:
print(x_test)

[[0.0 1.0 0.0 85.0 -0.8733675687734604]
 [1.0 0.0 0.0 150.0 1.2790884442427946]]
